/* !file overlay29 */
/* ApplyMoveEffect = ?????; unknown */
ApplyMoveEffectHookAddr = 0x023302E4;
ApplyMoveEffectJumpAddr = 0x0233310C;
ApplyItemEffectHookAddr = 0x0231C434;
ApplyItemEffectJumpAddr = 0x0231D574;

/* Add your own symbols here... */

/* !file arm9 */
ChangeGlobalBorderColor = 0x02027D74;

SetBrightnessMain = 0x022eb1e0;
SetBrightnessSub = 0x022eb214;
SetBrightnessNonblocking = 0x022eb14c;
SetBrightness = 0x02008f3c;